#!/bin/bash

#!/bin/bash

mailqueue=$(mailq)
msg_not_sent=$(grep -i 'rejected|refused' /var/log/maillog | wc -l)
msg_sent=$(grep -i 'sent' /var/log/maillog | wc -l)

echo -e "Mailqueue reporting:\n $mailqueue=$(mailq),\n\nTotal mails sent: $msg_sent,\n\nNo. of mails either rejected or refused: $msg_not_sent " | mutt -s "mailq and maillog from $HOSTNAME for `date +%A-%D`"  <email_id>
